# Generated by Django 4.0.6 on 2023-01-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('receiver_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blood', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pin', models.IntegerField()),
                ('weight', models.CharField(max_length=255)),
                ('bp', models.CharField(max_length=255)),
                ('prevreceive', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('req', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('donor_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blood', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pin', models.IntegerField()),
                ('weight', models.CharField(max_length=255)),
                ('bp', models.CharField(max_length=255)),
                ('prevdonation', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('req', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
