# Generated by Django 4.0.6 on 2023-01-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onebloodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='req',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='req',
        ),
        migrations.CreateModel(
            name='blood_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onebloodapp.donor')),
                ('rec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onebloodapp.receiver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
