# Generated by Django 4.0.6 on 2023-01-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onebloodapp', '0002_remove_donor_req_remove_receiver_req_blood_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('bloger_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='blood_req',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donordetail', to='onebloodapp.donor'),
        ),
        migrations.AlterField(
            model_name='blood_req',
            name='rec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverdetail', to='onebloodapp.receiver'),
        ),
    ]
